main:
  - name: "Home"
    url: "/"
    weight: 10

  - name: "Projects"
    url: "/projects/"
    weight: 20

  - name: "Publications"
    url: "/publications/"
    weight: 30

  - name: "Our Team"
    url: "/people/"
    weight: 40

  - name: "News & Events"
    url: "/#news"
    weight: 50

  - name: Contact
    url: /contact/
    weight: 60

# Our Team 서브메뉴
people:
  - name: Members
    url: /people/
    weight: 1
    parent: Our Team
    
  - name: Emotional Support Team
    url: /pets/
    weight: 2
    parent: Our Team
