main:
  - name: "Home"
    url: "/"
    weight: 10

  - name: "Our Team"
    url: "/#team"
    weight: 20

  - name: "Research"
    url: "/#research"
    weight: 30

  - name: "Publications"
    url: "/#publications"
    weight: 40

  - name: "News & Events"
    url: "/#news"
    weight: 50

  - name: "FAQs"
    url: "/#faqs"
    weight: 60

  - name: "Join Us"
    url: "/#join"
    weight: 70
